name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Test
      run: dotnet test

    - name: Build Example Reports
      run: dotnet run --project src/app report **/bin/**/dotnet*.dll -o ./example-report-site --framework net8.0 

    - name: Commit & Push report
      if: github.ref != 'refs/heads/main'
      run: |
        git config --global user.email "automatic@push.com"
        git config --global user.name "Automatic Push"
        git add example-report-site
        git commit -m "Automatic report update"
        git push

  publish-to-nuget:
    name: Package & Publish to NuGet (main)
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Generate .nupkg
      run: dotnet pack -o ./artifacts

    - name: Publish to NuGet if main branch
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://api.nuget.org/v3/index.json
    
